[2021-07-15 11:35:55,757] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Treino-02.get-data 2021-07-14T11:02:00+00:00 [queued]>
[2021-07-15 11:35:55,770] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Treino-02.get-data 2021-07-14T11:02:00+00:00 [queued]>
[2021-07-15 11:35:55,770] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 11:35:55,770] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-15 11:35:55,771] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 11:35:55,786] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): get-data> on 2021-07-14T11:02:00+00:00
[2021-07-15 11:35:55,791] {standard_task_runner.py:52} INFO - Started process 8449 to run task
[2021-07-15 11:35:55,795] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Treino-02', 'get-data', '2021-07-14T11:02:00+00:00', '--job-id', '1558', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/treino02.py', '--cfg-path', '/tmp/tmp81409n3u', '--error-file', '/tmp/tmpmmm7r2s6']
[2021-07-15 11:35:55,796] {standard_task_runner.py:77} INFO - Job 1558: Subtask get-data
[2021-07-15 11:35:55,841] {logging_mixin.py:104} INFO - Running <TaskInstance: Treino-02.get-data 2021-07-14T11:02:00+00:00 [running]> on host 07e9e45ed309
[2021-07-15 11:35:55,923] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=bruno@***.com.br,bruno@bruno.com.br
AIRFLOW_CTX_DAG_OWNER=Bruno - IGTI
AIRFLOW_CTX_DAG_ID=Treino-02
AIRFLOW_CTX_TASK_ID=get-data
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T11:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-14T11:02:00+00:00
[2021-07-15 11:35:55,924] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-15 11:35:55,925] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'curl https://raw.githubusercontent.com/A3Data/hermione/master/hermione/file_text/train.csv -o ~/train.csv']
[2021-07-15 11:35:55,946] {subprocess.py:75} INFO - Output:
[2021-07-15 11:35:55,962] {subprocess.py:79} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2021-07-15 11:35:55,963] {subprocess.py:79} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2021-07-15 11:35:56,208] {subprocess.py:79} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /home/***/train.csv: Permission denied
[2021-07-15 11:35:56,208] {subprocess.py:79} INFO - 100    14  100    14    0     0     56      0 --:--:-- --:--:-- --:--:--    56
[2021-07-15 11:35:56,209] {subprocess.py:79} INFO - curl: (23) Failed writing body (0 != 14)
[2021-07-15 11:35:56,210] {subprocess.py:83} INFO - Command exited with return code 23
[2021-07-15 11:35:56,227] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-15 11:35:56,232] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Treino-02, task_id=get-data, execution_date=20210714T110200, start_date=20210715T113555, end_date=20210715T113556
[2021-07-15 11:35:56,293] {local_task_job.py:151} INFO - Task exited with return code 1
